package com.liferay.portal.audit.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.audit.model.AuditEvent;
import com.liferay.portal.audit.service.AuditEventLocalService;
import com.liferay.portal.audit.service.persistence.AuditEventFinder;
import com.liferay.portal.audit.service.persistence.AuditEventPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the audit event local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.audit.service.impl.AuditEventLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.audit.service.impl.AuditEventLocalServiceImpl
 * @see com.liferay.portal.audit.service.AuditEventLocalServiceUtil
 * @generated
 */
public abstract class AuditEventLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements AuditEventLocalService,
        IdentifiableBean {
    @BeanReference(type = AuditEventLocalService.class)
    protected AuditEventLocalService auditEventLocalService;
    @BeanReference(type = AuditEventPersistence.class)
    protected AuditEventPersistence auditEventPersistence;
    @BeanReference(type = AuditEventFinder.class)
    protected AuditEventFinder auditEventFinder;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private AuditEventLocalServiceClpInvoker _clpInvoker = new AuditEventLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.portal.audit.service.AuditEventLocalServiceUtil} to access the audit event local service.
     */

    /**
     * Adds the audit event to the database. Also notifies the appropriate model listeners.
     *
     * @param auditEvent the audit event
     * @return the audit event that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public AuditEvent addAuditEvent(AuditEvent auditEvent)
        throws SystemException {
        auditEvent.setNew(true);

        return auditEventPersistence.update(auditEvent, false);
    }

    /**
     * Creates a new audit event with the primary key. Does not add the audit event to the database.
     *
     * @param auditEventId the primary key for the new audit event
     * @return the new audit event
     */
    public AuditEvent createAuditEvent(long auditEventId) {
        return auditEventPersistence.create(auditEventId);
    }

    /**
     * Deletes the audit event with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param auditEventId the primary key of the audit event
     * @return the audit event that was removed
     * @throws PortalException if a audit event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public AuditEvent deleteAuditEvent(long auditEventId)
        throws PortalException, SystemException {
        return auditEventPersistence.remove(auditEventId);
    }

    /**
     * Deletes the audit event from the database. Also notifies the appropriate model listeners.
     *
     * @param auditEvent the audit event
     * @return the audit event that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public AuditEvent deleteAuditEvent(AuditEvent auditEvent)
        throws SystemException {
        return auditEventPersistence.remove(auditEvent);
    }

    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(AuditEvent.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return auditEventPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return auditEventPersistence.findWithDynamicQuery(dynamicQuery, start,
            end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return auditEventPersistence.findWithDynamicQuery(dynamicQuery, start,
            end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return auditEventPersistence.countWithDynamicQuery(dynamicQuery);
    }

    public AuditEvent fetchAuditEvent(long auditEventId)
        throws SystemException {
        return auditEventPersistence.fetchByPrimaryKey(auditEventId);
    }

    /**
     * Returns the audit event with the primary key.
     *
     * @param auditEventId the primary key of the audit event
     * @return the audit event
     * @throws PortalException if a audit event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public AuditEvent getAuditEvent(long auditEventId)
        throws PortalException, SystemException {
        return auditEventPersistence.findByPrimaryKey(auditEventId);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return auditEventPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the audit events.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of audit events
     * @param end the upper bound of the range of audit events (not inclusive)
     * @return the range of audit events
     * @throws SystemException if a system exception occurred
     */
    public List<AuditEvent> getAuditEvents(int start, int end)
        throws SystemException {
        return auditEventPersistence.findAll(start, end);
    }

    /**
     * Returns the number of audit events.
     *
     * @return the number of audit events
     * @throws SystemException if a system exception occurred
     */
    public int getAuditEventsCount() throws SystemException {
        return auditEventPersistence.countAll();
    }

    /**
     * Updates the audit event in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param auditEvent the audit event
     * @return the audit event that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public AuditEvent updateAuditEvent(AuditEvent auditEvent)
        throws SystemException {
        return updateAuditEvent(auditEvent, true);
    }

    /**
     * Updates the audit event in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param auditEvent the audit event
     * @param merge whether to merge the audit event with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the audit event that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public AuditEvent updateAuditEvent(AuditEvent auditEvent, boolean merge)
        throws SystemException {
        auditEvent.setNew(false);

        return auditEventPersistence.update(auditEvent, merge);
    }

    /**
     * Returns the audit event local service.
     *
     * @return the audit event local service
     */
    public AuditEventLocalService getAuditEventLocalService() {
        return auditEventLocalService;
    }

    /**
     * Sets the audit event local service.
     *
     * @param auditEventLocalService the audit event local service
     */
    public void setAuditEventLocalService(
        AuditEventLocalService auditEventLocalService) {
        this.auditEventLocalService = auditEventLocalService;
    }

    /**
     * Returns the audit event persistence.
     *
     * @return the audit event persistence
     */
    public AuditEventPersistence getAuditEventPersistence() {
        return auditEventPersistence;
    }

    /**
     * Sets the audit event persistence.
     *
     * @param auditEventPersistence the audit event persistence
     */
    public void setAuditEventPersistence(
        AuditEventPersistence auditEventPersistence) {
        this.auditEventPersistence = auditEventPersistence;
    }

    /**
     * Returns the audit event finder.
     *
     * @return the audit event finder
     */
    public AuditEventFinder getAuditEventFinder() {
        return auditEventFinder;
    }

    /**
     * Sets the audit event finder.
     *
     * @param auditEventFinder the audit event finder
     */
    public void setAuditEventFinder(AuditEventFinder auditEventFinder) {
        this.auditEventFinder = auditEventFinder;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.liferay.portal.audit.model.AuditEvent",
            auditEventLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.liferay.portal.audit.model.AuditEvent");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return AuditEvent.class;
    }

    protected String getModelClassName() {
        return AuditEvent.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = auditEventPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
